#!/usr/bin/env sh
{ pkill -f mpd ; rm $HOME/.mpd/mpd.db ; touch $HOME/.mpd/mpd.db ; mpd ; ($HOME/mpd-loop & mpdkeys &) ; } > /dev/null 2>&1 ; osascript -e 'quit app "Emacs"' ; sleep 1 ; open -a Emacs
