#!/usr/bin/env sh
{
        pkill -f mpd
        > $HOME/.mpd/mpd.db
        mpd
        ($HOME/mpd-loop &)
        (mpdkeys &)
        osascript -e 'quit app "Emacs"'
        sleep 1
        open -a Emacs
} > /dev/null 2>&1
